### ISSUE TITLE
run_branches.pl like runner that allows multiple trees and multiple configs

### ISSUE THREAD

**Issue by anarazel** [PGBuildFarm/client-code#11]
Currently I've a buildfarm machine that hosts like 5 animals, with one of them being very slow & expensive.  It now has a decent amount of cores and CPUs available, so I'd like to be able to efficiently run multiple branches at the same time.  That's especially important for skink, which takes ~6h on master due to the use of valgrind.

run_branches.pl doesn't currently allow for parallelism, so I'd have to setup a cron-job that runs all branches manually.  But that has the worst case potential of running like 5 animals * 6 branches at once, when a commit is backpatched all the way - that's obviously too much.

Additionally using separate run_branches.pl invocations builds the most "urgent" branch for each animal separately, but doesn't take into account that there might be more urgent branches for other animals.

What I think would be useful, is one script that a) allows to run multiple animals b) internally understands parallelism.   I can code something up for that myself, but it seems more useful to do that in the buildfarm tree.  An opinions on how to do that best?  Locally I'd probably code something up using gnu parallel, but that's probably not acceptable?

**Comment by adunstan** [comment]
Step one would probably be to add a --run-parallel option to run_branches. That would be for a single animal. That should be pretty simple. The main difficulty would be the next step of limiting parallelism, possibly across animals, to some number in a robust way. We'd have to designate a way of counting the running branches and waiting. Maybe a temp file that auto-deletes would do the trick.

**Comment by vbwagner** [comment]
I have similar problem, which is much worse, because I run lots of animals on one machine using LXC containers for linuxes and KVM virtual machines for other OS es.

I've dealt with this problem running small web-server on the host which reports OK if load average less than configured value and OVERLOADED if not.

And my cron jobs look like

`cd client&& [ "`curl http://192.168.100.1:8000/ 2>/dev/null `" = "OK" ] &&  ./run_branches.pl --run-all
`
If you don't use this containerization, you can just check LA direclly from cron command line. 
In practice one need to prevent new jobs to start if load average exceeds 10, provided that they don't start at same moment and one job have at least 5 minutes to bootstrap until second checks for LA.

**Comment by adunstan** [comment]
Closing in the absence of further activity.
